//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websiteBALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietLuong
    {
        public string MaChiTietBangLuong { get; set; }
        public string NhanVien_MNV { get; set; }
        public string Luong_MaLuong { get; set; }
        public Nullable<double> LuongCoBan { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> PhuCap { get; set; }
        public Nullable<double> TienThuong { get; set; }
        public Nullable<double> TienPhat { get; set; }
        public Nullable<System.DateTime> NgayNhanLuong { get; set; }
        public Nullable<double> TongTienLuong { get; set; }
        public Nullable<double> SoNgayDiLam { get; set; }
    }
}
