//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websiteBALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public int madonhang { get; set; }
        public int Mabalo { get; set; }
        public Nullable<int> soluong { get; set; }
        public string dongia { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual DONHANG DONHANG1 { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
