//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websiteBALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public int MaLuong { get; set; }
        public Nullable<double> LuongToiThieu { get; set; }
        public Nullable<double> HeSoLuong { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> PhuCap { get; set; }
        public Nullable<int> SoNgayDiLam { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string NhanVien_MNV { get; set; }
        public Nullable<double> TongLuong { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
