//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websiteBALO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUONGHIEUSP
    {
        public int MaTH { get; set; }
        public string TenTH { get; set; }
        public string xuatxu { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
    }
}
